const D=window.MDMER_DATA,$=s=>document.querySelector(s),e=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),uniq=a=>[...new Set(a.filter(Boolean))].sort(),ln=(u,t)=>u?`<a class="src" href="${e(u)}" target="_blank">${t} ↗</a>`:'';
$('#nRecords').textContent=D.meta.record_count;$('#nDatasets').textContent=D.meta.dataset_count;$('#years').textContent=D.meta.year_min+'–'+D.meta.year_max;
function fill(id,a){a.forEach(v=>{let o=document.createElement('option');o.value=v;o.textContent=v;$(id).appendChild(o)})}fill('#tier',uniq(D.records.map(r=>r['Evidence Relevance Tier'])));fill('#type',uniq(D.records.map(r=>r['Record Type'])));fill('#role',uniq(D.records.map(r=>r['Evidence Role'])));
function render(){let q=$('#q').value.toLowerCase(),t=$('#tier').value,ty=$('#type').value,ro=$('#role').value;let rows=D.records.filter(r=>(!q||Object.values(r).join(' ').toLowerCase().includes(q))&&(!t||r['Evidence Relevance Tier']==t)&&(!ty||r['Record Type']==ty)&&(!ro||r['Evidence Role']==ro));$('#visible').textContent=rows.length;$('#rows').innerHTML=rows.map(r=>`<tr><td>${e(r['Record ID'])}</td><td>${e(r.Year)}</td><td><div class="title">${e(r['Title / Dataset'])}</div><div class="meta">${e(r['Primary Authors / Source'])}${r['Institution / Dataset Owner']?' · '+e(r['Institution / Dataset Owner']):''}</div></td><td>${e(r['Modalities / Signals'])}</td><td>${e(r['Interaction Level'])}</td><td>${e(r['Task / Paradigm'])}</td><td><span class="tag">${e(r['Evidence Role'])}</span></td><td>${ln(r['Paper / Reference URL'],'Paper')}${ln(r['Dataset / Access URL'],'Data')}</td></tr>`).join('')}
['#q','#tier','#type','#role'].forEach(id=>$(id).addEventListener('input',render));$('#reset').onclick=()=>{['#q','#tier','#type','#role'].forEach(id=>$(id).value='');render()};render();
let pref=['GroupAffect-4','CogniModal-D','Puzzle-STAMPS','Kennedy','Physiological linkage','K-EmoCon','AMIGOS','RECOLA'];let comps=[];pref.forEach(p=>{let x=D.comparators.find(r=>r['Comparator / Study'].toLowerCase().includes(p.toLowerCase()));if(x&&!comps.includes(x))comps.push(x)});
$('#cards').innerHTML=comps.map((r,i)=>`<article class="card"><small>EXTERNAL COMPARATOR ${i+1}</small><h3>${e(r['Comparator / Study'])}</h3><p>${e(r['Participants / Interaction'])} · ${e(r['Primary Task / Paradigm'])}</p><div class="divider"><b>Closest overlap</b><p>${e(r['Closest ARL Overlap'])}</p></div><div class="divider"><b>Critical difference</b><p>${e(r['Critical Difference vs Proposed ARL'])}</p></div>${ln(r['Primary Source URL'],'Primary source')}${ln(r['Data / Access URL'],'Dataset')}</article>`).join('');
$('#verdicts').innerHTML=D.gap_verdicts.map(v=>`<article class="verdict"><span class="status">${e(v['Challenge Result'])}</span><h3>${e(v['Candidate Gap'])}</h3><p>${e(v.Interpretation)}</p></article>`).join('');
$('#arlTags').innerHTML=[...D.arl.modalities,...D.arl.features].map(x=>`<span class="tag">${e(x)}</span>`).join('');
comps.forEach((r,i)=>{let o=document.createElement('option');o.value=i;o.textContent=r['Comparator / Study'];$('#compareSel').appendChild(o)});
function comp(){let r=comps[Number($('#compareSel').value)||0],m=[['Participants / interaction',r['Participants / Interaction'],D.arl.participants],['Task',r['Primary Task / Paradigm'],D.arl.task],['EEG',r.EEG,'Yes'],['Cardiac',r['ECG / PPG / HR'],'ECG'],['EDA / GSR',r['EDA / GSR'],'Yes'],['EMG',r.EMG,'Yes'],['Eye tracking',r['Eye Tracking'],'Yes'],['Audio',r.Audio,'Yes'],['Video',r.Video,'Yes'],['Repeated',r['Repeated / Multi-round?'],'Yes'],['Confidence',r['Confidence / Self-report'],'Explicit confidence'],['Deception',r['Deception / Strategic Misinfo?'],'Yes'],['Synchronization',r['Synchronization / Alignment'],D.arl.synchronization]];$('#compareBody').innerHTML=`<h3>${e(r['Comparator / Study'])} vs proposed ARL</h3>`+m.map(x=>`<div class="crow"><strong>${e(x[0])}</strong><div class="cell">${e(x[1]||'Not reported')}</div><div class="cell arl">${e(x[2])}</div></div>`).join('')+`<p><b>Why it still differs:</b> ${e(r['Critical Difference vs Proposed ARL'])}</p>`}$('#compareSel').onchange=comp;comp();